events {}

http {
    server {
        listen 80;

        location /service1/ {
            proxy_pass http://microservices-cpp-service1-1:5000/;
        }

        location /service2/ {
            proxy_pass http://microservices-cpp-service2-1:5001/;
        }
    }
}