services:
  service1:
    build: ./service1
    ports:
      - "5000:5000"

  service2:
    build: ./service2
    ports:
      - "5001:5001"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf